[tools]
lua = "5.1"
node = "25.3"
"npm:@anthropic-ai/claude-code" = "2.1.29"
"npm:@derekstride/tree-sitter-sql" = "latest"
"npm:@playwright/mcp" = "latest"
"npm:npm-check-updates" = "latest"
python = "3.13"
ruby = "latest"

[settings]
idiomatic_version_file_enable_tools = []
